const fallbackDSL = {
  version: '1.0',
  canvas: { width: 390, height: 844 },
  theme: 'night',
  mode: 'static',
  background: {
    type: 'gradient',
    value: 'linear-gradient(180deg, #0f172a 0%, #020617 100%)',
  },
  layers: [
    {
      id: 'ambient-glow',
      type: 'shape',
      shape: 'blob',
      x: -70,
      y: 420,
      width: 270,
      height: 270,
      color: 'rgba(56, 189, 248, 0.2)',
      opacity: 0.75,
      animation: 'pulse',
    },
    {
      id: 'moon',
      type: 'shape',
      shape: 'circle',
      x: 286,
      y: 82,
      width: 58,
      height: 58,
      color: 'rgba(255,255,255,0.9)',
      opacity: 0.92,
      animation: 'float',
    },
    {
      id: 'star-1',
      type: 'shape',
      shape: 'star',
      x: 72,
      y: 104,
      width: 12,
      height: 12,
      color: '#f8fafc',
      opacity: 0.85,
      animation: 'pulse',
    },
    {
      id: 'star-2',
      type: 'shape',
      shape: 'star',
      x: 118,
      y: 302,
      width: 8,
      height: 8,
      color: '#bae6fd',
      opacity: 0.7,
    },
    {
      id: 'star-3',
      type: 'shape',
      shape: 'star',
      x: 320,
      y: 282,
      width: 10,
      height: 10,
      color: '#ffffff',
      opacity: 0.78,
    },
    {
      id: 'planet-material',
      type: 'asset',
      assetId: 'doodle-091',
      src: '/materials/svg/doodle-91.svg',
      x: 246,
      y: 300,
      width: 112,
      height: 112,
      fit: 'contain',
      rotation: 8,
      opacity: 0.95,
      animation: 'float',
      effects: {
        shadow: 'soft',
        glow: 'blue',
      },
    },
    {
      id: 'time',
      type: 'text',
      role: 'time',
      content: '18:30',
      x: 195,
      y: 176,
      fontSize: 76,
      fontWeight: 750,
      color: '#ffffff',
      align: 'center',
    },
    {
      id: 'date',
      type: 'text',
      role: 'date',
      content: 'Thursday, June 11',
      x: 195,
      y: 248,
      fontSize: 18,
      fontWeight: 450,
      color: 'rgba(255,255,255,0.78)',
      align: 'center',
    },
    {
      id: 'weather',
      type: 'widget',
      role: 'weather',
      x: 32,
      y: 690,
      width: 326,
      height: 104,
      style: 'glass',
      content: {
        title: '今日天气',
        main: '26°C · Cloudy',
        icon: '☁',
      },
    },
  ],
}

export default fallbackDSL
